# -*- coding: utf-8 -*-
"""DataIMG-check.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16H_5fmtdWYzDBZA8mmTrAQNs-b7FbMrl

把圖片跟標籤分別做成兩個list
"""

import os
dirjpg = list(os.listdir("D:\yolov3\keras-yolo3-master\new\train_image_folder"))
dirxml = list(os.listdir("D:\yolov3\keras-yolo3-master\new\train_annot_folder"))

"""拆掉副檔名，並且做差集比對，xml的list多了個rell，保險起見先拿掉"""

for i in range(len(dirjpg)):
    dirjpg[i] = dirjpg[i].replace(".jpg", "")

for i in range(len(dirxml)):
    dirxml[i] = dirxml[i].replace(".xml", "")


x = list(set(dirjpg).difference(set(dirxml)))
print(x)

y = list(set(dirxml).difference(set(dirjpg)))
# y.remove("re11")
print(y)

"""刪除目的端的list內資料"""

# !rm /content/drive/Shareddrives/北科上課影片/圖片與標籤/標籤/"441 (1)".xml
# for i in x:
#     os.system("rm /content/drive/Shareddrives/北科上課影片/圖片與標籤/標籤/'" + i + "'.jpg")
#
# for i in y:
#     os.system("rm /content/drive/Shareddrives/北科上課影片/圖片與標籤/標籤/'" + i + "'.xml")

# !cp /content/drive/MyDrive/img/valid_image/imglabel/421.xml /content

from bs4 import BeautifulSoup

error_list = []

path_main = "D:\yolov3\keras-yolo3-master\new\train_annot_folder"
path_test = "D:\yolov3\keras-yolo3-master\new\train_image_folder"

label_name = ["Friedsteak", "Friedchickenlegs", "chickenlegs", "Fish", "Slicedmeat", "Shrimp", "Friedshrimp", "chicken", "sausage", "pork", "ribs", "egg", "halfegg", "sunegg", "omelet", "broccoli", "cauliflower", "Cabbage", "carrot", "Fungus", "Beansprouts", "riceflour", "Driedtofu", "tofu", "corn", "green", "Bambooshoots", "Shiitake", "pumpkin", "eggplant", "shelledShrimp"]
dirxml_ = list(os.listdir(path_main))

for i in dirxml_:
    print(i)
    f = open(path_main + i, "r")
    read = f.read()
    f.close()

    xml = BeautifulSoup(read)
    labels = xml.find_all("name")
    labels = list(labels)


    for label_ in labels:
        if label_.get_text() not in label_name:
            x = "檔案名稱: "+ i +"標籤名稱: " + str(label_)
            error_list.append(x)

print("over")

print(error_list)

x = r"['Bambooshoots', 'Beansprouts', 'Cabbage', 'Driedtofu', 'Fish', 'Friedchickenlegs', 'Friedshrimp', 'Friedsteak', 'Fungus', 'Shiitake', 'Shrimp', 'Slicedmeat', 'broccoli', 'carrot', 'cauliflower', 'chicken', 'chickenlegs', 'corn', 'egg', 'eggplant', 'green', 'halfegg', 'omelet', 'pork', 'pumpkin', 'ribs', 'riceflour', 'sausage', 'shelledShrimp', 'sunegg', 'tofu']"

x.replace(r"'", r'"')
x